jobs:
  - name: build-bosh-docker
    public: true
    serial: true
    plan:
      - aggregate:
        - get: bosh-src
          trigger: true
#          passed:
#            - "build-main-ruby-go"
        - get: bosh-cli
        - get: bosh-deployment
      - task: copy-dependencies
        file: bosh-src/ci/pipelines/docker-images/tasks/copy-bosh-docker-dependencies.yml
      - put: main-bosh-docker
        input_mapping:
          - bosh-src: bosh-src-with-docker-dependencies
        params:
          build: "bosh-src/ci/docker/main-bosh-docker"
          tag: "dev"
        get_params:
          skip_download: true

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: wip-docker-image

  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master

  - name: bosh-cli
    type: s3
    source:
      regexp: alpha-bosh-cli-(.*)-linux-amd64
      bucket: {{bosh_cli_aws_s3_alpha_release_bucket}}
      region_name: {{bosh_cli_aws_s3_release_bucket_region}}

  - name: main-bosh-docker
    type: docker-image
    source:
      repository: bosh/main-bosh-docker
      email: {{dockerhub_email}}
      username: {{dockerhub_username}}
      password: {{dockerhub_password}}
